# Generated by Django 5.0.8 on 2024-08-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
