# Generated by Django 5.0.8 on 2024-08-14 17:39

import myapp.utils.image_utils
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.Post.image_upload, validators=[myapp.utils.image_utils.validate_image_size]),
        ),
    ]
