# Generated by Django 5.0.8 on 2024-08-21 16:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('followed_by', 'following')},
        ),
    ]
